### ISSUE TITLE
Implementing cache.

### ISSUE THREAD

**Issue by stephpy** [florianv/FlorianvSwapBundle#1]
Hi,

I would like to use the awesome swap library, but i have to cache rates. I see it's done in master of `florianv/swap` and it's a good thing. Do you schedule to tag a new version of this library ?

If you're OK, I can make an implementation of `florianv/swap` with cache in this bundle.

```
florianv_swap:
    cache:
        doctrine: # Doctrine bundle config.
             type: array
             host: ~
             port:  ~
             instance_class: ~
             class: ~
             id: ~
    providers:
        google_finance: ~
```

**Edit: I see you already tagged a 2.x version of swag :+1:, implementation of cache on swap-bundle could result to a 2.x version on the bundle too.**

Thoughts ?
